### ISSUE TITLE
Can't watch week2's lecture and slides--access denied

### ISSUE THREAD

**Issue by jinfei1125** [UChicago-CCA-2021/Frequently-Asked-Questions#15]
Hi, when I click the 'Slides & Lectures' button on week2, it said access denied. Am I the only one? My CNet ID: jinfei
<img width="607" alt="acess_denied" src="https://user-images.githubusercontent.com/72103935/105415611-f67edb00-5c06-11eb-8fe3-2818b9f8c5c1.png">
↓
![图片](https://user-images.githubusercontent.com/72103935/105415751-28903d00-5c07-11eb-811a-3679777577f8.png)

**Comment by theoevans1** [comment]
I'm having the same issue.

**Comment by bhargavvader** [comment]
@HyunkuKwon has this been resolved?

**Comment by HyunkuKwon** [comment]
Yup I fixed it!

2021년 1월 23일 (토) 오전 3:52, Bhargav Srinivasa Desikan <
notifications@github.com>님이 작성:
