### ISSUE TITLE
Can't find data sets for 5 senators or spam emails

### ISSUE THREAD

**Issue by theoevans1** [UChicago-CCA-2021/Frequently-Asked-Questions#28]
For this week's homework, I can't locate two of the data sets: the Senate press releases with 5 Senators, or the emails classified as spam. Are they in the homework repository somewhere? Is there another way I should try to load them?
![Screen Shot 2021-02-09 at 2 11 35 PM](https://user-images.githubusercontent.com/68713830/107422806-240dc480-6ae1-11eb-81fa-c0be5daf9e34.png)

**Comment by bhargavvader** [comment]
Updated - huh, it seems like they were somehow missed when I was uploading data. 
I've added them now - I made sure to double-check for all the upcoming notebooks too, so you won't have this problem again!

**Comment by theoevans1** [comment]
Great, thank you!
