### ISSUE TITLE
Can we get more detail on the final project requirements?

### ISSUE THREAD

**Issue by jacyanthis** [UChicago-CCA-2021/Frequently-Asked-Questions#32]
Specifically, I see in the syllabus, "detailed 20 page research appendix that contains methodological justification and description, descriptive data and analysis, interpretation of findings and conclusion." 20 pages is a lot for a final paper, especially in a methods class. Is this meant to include visualizations (copied from our annotated code file)? Double-spaced? Include a reference list? etc. If so, 20 pages seems reasonable.

**Comment by bhargavvader** [comment]
Yup, it's 20 pages including all of that!
